# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-10 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100, verbose_name='Link')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('text', models.TextField(verbose_name='Descrição')),
                ('date_post', models.DateField(null=True, verbose_name='Postado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
    ]
