# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-11 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='date_post',
        ),
        migrations.AddField(
            model_name='evento',
            name='date_evento',
            field=models.DateField(null=True, verbose_name='Data do evento'),
        ),
    ]
