# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-10 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('text', models.TextField(verbose_name='Texto')),
                ('date_post', models.DateField(null=True, verbose_name='Postado em')),
                ('image', models.ImageField(null=True, upload_to='blog/images', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
